package com.bydmr.navigation


import android.os.Bundle
import androidx.fragment.app.Fragment
import android.view.LayoutInflater
import android.view.View
import android.view.ViewGroup
import androidx.navigation.Navigation
import kotlinx.android.synthetic.main.fragment_camera.*
import java.util.*

class CameraFragment : Fragment() {

    override fun onCreateView(inflater: LayoutInflater, container: ViewGroup?, savedInstanceState: Bundle?): View? {
        // Inflate the layout for this fragment
        return inflater.inflate(R.layout.fragment_camera, container, false)
    }

    override fun onViewCreated(view: View, savedInstanceState: Bundle?) {
        super.onViewCreated(view, savedInstanceState)

        buttonPhotos.setOnClickListener {
            val random = Random()

            // AutoGenerated class
            val nextAction = CameraFragmentDirections.nextAction()
            nextAction.numOfPhotos = random.nextInt(100)

            // İlişkili olduğu view üzerinden Navigation Controller'ı saptar
            Navigation.findNavController(it).navigate(nextAction)
        }
    }


}
